trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-latest

variables:
# variables to be used to trigger QE testing pipelines
  # project_name: "TAF-TEST"
  # pipeline_id: 165
# Loadrunner
  # project_name_ld: "loadrunner-cloud"
  # pipeline_id_ld: 127
# Generic
  sdfx_version: latest
  node_version: 16.17.0
  # sonar_service_connection: 'psecom-platform-devv-sonar'

stages:
  - stage: QA_Release
    dependsOn: Snyk
    condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'Manual'))
    variables:
      - group: qa-variable-group   
    jobs:
      - job: Deploy
        steps:
        - checkout: self
          path: https://github.com/Asda-eCom/asda-care-sfsc
        - template: 'templates/template_salesforce_authentication.yml'
          parameters:
            sdfx_version: $(sdfx_version)
            node_version: $(node_version)
            secure_file_variable_name: 'server.key1'
            username: $(username)
            instance_url: $(instanceurl)
            client_id: $(clientid)
            environment_name: 'qa'

        - template: 'templates/template_salesforce_deployment.yml'
          parameters:
            environment_name: 'qa'