trigger:
  - master

pr: none

pool:
  vmImage: "windows-latest"

parameters:
  - name: upperLimit
    displayName: "Quality Gates Upper Limit"
    type: int
    defaults: 90

  - name: lowerLimit
    displayName: "Quality Gates Upper Limit"
    type: int
    defaults: 80

stages:
  - stage: first_stage
    jobs:
      - job: FIRST_JOB
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo "Checking complete"

          - template: "./template.yml"

          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                echo 'Hello World'
                echo ${{parameters.upperLimit}}
                echo ${{parameters.lowerLimit}}

          - task: Bash@3
            displayName: First Check within same JOB
            inputs:
              targetType: "inline"
              script: |
                echo $(PythonScript.myVar)

  - stage: Manual_Approval
    dependsOn: first_stage
    condition: and(eq(variables['checker'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      - name: checker
        value: $[ dependencies.first_stage.outputs['FIRST_JOB.PythonScript.MyVar'] ]
    jobs:
      - deployment: A
        displayName: Check Approval
        environment: "dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: echo "Manual Approval done"
                  name: varCheck

  - stage: Second_Stage
    dependsOn: Manual_Approval
    condition: and(not(failed()), not(canceled()))
    variables:
      - name: checker
        value: $[ stageDependencies.first_stage.FIRST_JOB.outputs['PythonScript.MyVar'] ]
    jobs:
      - job: Next_Stage
        steps:
          - task: Bash@3
            displayName: Next Stage Skip Test
            inputs:
              targetType: "inline"
              script: |
                echo "Hello World!"
                echo $(Build.SourceBranch)
