trigger:
  - master

pr: none

pool:
  vmImage: "windows-latest"

stages:
  - stage: first_stage
    variables:
      - group: dev-variable-group
    jobs:
      - job: FIRST_JOB
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo "Checking complete"

          - template: "./template.yml"
            parameters:
              lowerLimit: $(dev-lower-limit)
              upperLimit: $(dev-upper-limit)

          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                echo 'Hello World'
                echo $(dev-lower-limit)
                echo $(dev-upper-limit)

          - task: Bash@3
            displayName: First Check within same JOB
            inputs:
              targetType: "inline"
              script: |
                echo $(PythonScript.myVar)


  - stage: Manual_Approval
    dependsOn: first_stage
    condition: and(eq(variables['checker'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      - name: checker
        value: $[ dependencies.first_stage.outputs['FIRST_JOB.PythonScript.MyVar'] ]
    jobs:
      - deployment: A
        displayName: Check Approval
        environment: "dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: echo "Manual Approval done"
                  name: varCheck


  - stage: Second_Stage
    dependsOn: Manual_Approval
    condition: and(not(failed()), not(canceled()))
    variables:
      - name: checker
        value: $[ stageDependencies.first_stage.FIRST_JOB.outputs['PythonScript.MyVar'] ]
    jobs:
      - job: Next_Stage
        steps:
          - task: Bash@3
            displayName: Next Stage Skip Test
            inputs:
              targetType: "inline"
              script: |
                echo "Hello World!"
                echo $(Build.SourceBranch)

  - stage: QA_STAGE
    dependsOn: Second_Stage
    condition: and(not(failed()), not(canceled()))
    variables:
      - group: dev-variable-group
    jobs:
      - job: QA_FIRST_JOB
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo "Checking complete"

          - template: "./template.yml"
            parameters:
              lowerLimit: $(qa-lower-limit)
              upperLimit: $(qa-upper-limit)

          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                echo 'Hello World'
                echo $(qa-lower-limit)
                echo $(qa-upper-limit)

          - task: Bash@3
            displayName: First Check within same JOB
            inputs:
              targetType: "inline"
              script: |
                echo $(PythonScript.myVar)

  - stage: Manual_Approval_Second
    dependsOn: QA_STAGE
    condition: and(eq(variables['checker'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      - name: checker
        value: $[ dependencies.QA_STAGE.outputs['QA_FIRST_JOB.PythonScript.MyVar'] ]
    jobs:
      - deployment: A
        displayName: Check Approval
        environment: "dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: echo "Manual Approval done"
                  name: varCheck

  - stage: QA_Second_Stage
    dependsOn: Manual_Approval_Second
    condition: and(not(failed()), not(canceled()))
    variables:
      - name: checker
        value: $[ stageDependencies.first_stage.FIRST_JOB.outputs['PythonScript.MyVar'] ]
    jobs:
      - job: Next_Stage
        steps:
          - task: Bash@3
            displayName: Next Stage Skip Test
            inputs:
              targetType: "inline"
              script: |
                echo "Hello World!"
                echo $(Build.SourceBranch)
