trigger:
  - master

pool:
  vmImage: "windows-latest"
    
stages:
  - stage: first_stage
    variables: 
      - name: checkVar
        value: false
      - name: pipelineId 
        value: null
    jobs:
      # - job: Building_Policies
      #   steps:
      #     - task: Bash@3
      #       inputs:
      #         targetType: 'inline'
      #         script: |
      #           # Write your commands here
      #           echo 'Hello world'

      - job: FIRST_JOB
        # dependsOn: Building_Policies
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo "Checking complete"
          
          - template: "./template.yml"
          
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo 'Hello World'
          
          - task: Bash@3
            displayName: 
            inputs:
              targetType: 'inline'
              script: |
                # echo $(averagePercentage) 
                echo $(checkVar)

      - job: waitForValidation
        variables:
          # - name : harsh
          #   value : hardeshm@publicisgroupe.net
          - name : ravi
            value : yenyelch@publicisgroupe.net
        displayName: Wait for external validation
        dependsOn: FIRST_JOB
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
            notifyUsers: | 
              # $(harsh)
              $(ravi)
            instructions: 'Please validate the build configuration and resume'
            onTimeout: 'resume'  

      - job: Check  
        dependsOn: waitForValidation 
        steps:
        - task: Bash@3
          displayName: 
          inputs:
            targetType: 'inline'
            script: |
              # echo $(averagePercentage) 
              echo $(checkVar)

            
