trigger:
  - master

pool:
  vmImage: "windows-latest"
    
stages:
  - stage: first_stage
    jobs:
      - job: Building_Policies
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo 'Hello world'

      - job: seeing_Policies
        dependsOn: Building_Policies
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo "Checking complete"
          
          - template: "./template.yml"
          
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo 'Hello World'


      - job: waitForValidation
        dependsOn: seeing_Policies
        displayName: Wait for external validation
        pool: server
        timeoutInMinutes: 60 # job times out in 3 days
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: 'venkatanagasairaviteja.yelchuri@publicissapient.com'
              instructions: 'Please validate the build configuration and resume'
              onTimeout: 'resume'
            

            
