trigger:
  - master

pool:
  vmImage: "windows-latest"
    
stages:
  - stage: first_stage
    variables:
      - name: myVar
        value: "-"
    jobs:
      # - job: Building_Policies
      #   steps:
      #     - task: Bash@3
      #       inputs:
      #         targetType: 'inline'
      #         script: |
      #           # Write your commands here
      #           echo 'Hello world'

      - job: FIRST_JOB
        # dependsOn: Building_Policies
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo "Checking complete"
          
          - template: "./template.yml"
          
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo 'Hello World'
          
          - task: Bash@3
            displayName: First Check within same JOB
            inputs:
              targetType: 'inline'
              script: |
                echo $(PythonScript.myVar) 
              
      - job: waitForValidation
        variables:
          # - name : harsh
          #   value : hardeshm@publicisgroupe.net
          - name : ravi
            value : yenyelch@publicisgroupe.net
        displayName: Wait for external validation
        dependsOn: FIRST_JOB
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
            notifyUsers: | 
              # $(harsh)
              $(ravi)
            instructions: 'Please validate the build configuration and resume'
            onTimeout: 'resume'  

      - job: Check  
        dependsOn: FIRST_JOB  
        variables: 
            myVarFromJobA: $[ dependencies.FIRST_JOB.outputs['PythonScript.myVar'] ] 
        steps:
        - task: Bash@3
          displayName: Second Check from different JOB
          inputs:
            targetType: 'inline'
            script: |
              echo $(myVarFromJobA) 

            
