trigger:
  - master

pool:
  vmImage: "windows-latest"
    
stages:
  - stage: first stage
    jobs:
      - job: Building_Policies
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo 'Hello world'

      - job: seeing_Policies
        
        steps:
          - task: Bash@3
            timeoutInMinutes: 1
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo "name         "
                sleep 60

      