trigger:
  - master

pool:
  vmImage: "windows-latest"
    
stages:
  - stage: first_stage
    jobs:
      - job: Building_Policies
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo 'Hello world'

      - job: seeing_Policies
        dependsOn: Building_Policies
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo "Checking complete"
          
          - template: "./template.yml"
          
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo 'Hello World'


          - task: ManualValidation@0
            timeoutInMinutes: 3
            inputs:
              notifyUsers: 'harshwardhanet7007@gmail.com'
              instructions: 'Please validate'
            

            
