trigger:
  - master

pool:
  vmImage: "windows-latest"

stages:
  - stage: first_stage
    jobs:
      - job: FIRST_JOB
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo "Checking complete"
          
          - template: "./template.yml"
          
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo 'Hello World'
                echo $(lower-limit)
                echo $(upper-limit)

          
          - task: Bash@3
            displayName: First Check within same JOB
            inputs:
              targetType: 'inline'
              script: |
                echo $(PythonScript.myVar) 

  - stage: Manual_Approval
    dependsOn: first_stage
    condition: and(eq(variables['checker'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      - name: checker
        value : $[ dependencies.first_stage.outputs['FIRST_JOB.PythonScript.MyVar'] ]
    jobs:
    - deployment: A
      # condition: and(succeeded(), eq(variables['checker'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      displayName: Check Approval
      environment: 'dev'
      strategy:                  
        runOnce:
          deploy:
            steps:
            - bash: echo $(checker)
              name: varCheck

  - stage: Second_Stage
    # dependsOn: first_stage
    condition: and(not(failed()), not(canceled()))
    variables:
      - name: checker
        value : $[ stageDependencies.first_stage.FIRST_JOB.outputs['PythonScript.MyVar'] ]
    jobs:
    - job: Next_Stage  
      steps:
      - task: Bash@3
        displayName: Next Stage Skip Test
        inputs:
          targetType: 'inline'
          script: |
            echo "Hello World!"
            echo $(Build.SourceBranch)
