trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-latest

variables:
# variables to be used to trigger QE testing pipelines
  # project_name: "TAF-TEST"
  # pipeline_id: 165
# Loadrunner
  # project_name_ld: "loadrunner-cloud"
  # pipeline_id_ld: 127
# Generic
  sdfx_version: latest
  node_version: 16.17.0
  # sonar_service_connection: 'psecom-platform-devv-sonar'

stages:
  - stage: Dev_Release
    jobs:
      - job: Deploy_dev
        steps:
        - checkout: self
          path: https://github.com/Asda-eCom/asda-care-sfsc
        - template: 'templates/template_salesforce_authentication.yml'
          parameters:
            sdfx_version: $(sdfx_version)
            node_version: $(node_version)
            secure_file_variable_name: 'server-key'
            username: 'hari.hari@asda.co.uk.devint'
            instance_url: 'https://test.salesforce.com'
            client_id: '3MVG9od6vNol.eBiDrTZrTxsmcowxzWUcil3NEMUbPOSM5FsHGQ_JGQ6qALOFOyLYp98LmIAINM.AsJKUJL.8'
            environment_name: 'devint'

        - template: 'templates/template_salesforce_deployment.yml'
          parameters:
            environment_name: 'devint'